//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiKOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiVietKOL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiVietKOL()
        {
            this.BinhLuanBVKOLs = new HashSet<BinhLuanBVKOL>();
            this.LuotThichBVKOLs = new HashSet<LuotThichBVKOL>();
        }
    
        public string Id { get; set; }
        public string MaBV { get; set; }
        public string TieuDe { get; set; }
        public string noidung { get; set; }
        public string anh { get; set; }
        public Nullable<System.DateTime> ngaydang { get; set; }
    
        public virtual KOL KOL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuanBVKOL> BinhLuanBVKOLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LuotThichBVKOL> LuotThichBVKOLs { get; set; }
    }
}
