//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiKOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuanBVKOL
    {
        public string MaBV { get; set; }
        public string IdKhach { get; set; }
        public string Noidung { get; set; }
        public Nullable<System.DateTime> ngaybl { get; set; }
        public int tutang { get; set; }
    
        public virtual BaiVietKOL BaiVietKOL { get; set; }
        public virtual khach khach { get; set; }
    }
}
