//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiKOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cautruc
    {
        public int mathaydoi { get; set; }
        public Nullable<int> ma { get; set; }
        public string anhnen { get; set; }
        public Nullable<decimal> koln1000 { get; set; }
        public Nullable<decimal> kol10005000 { get; set; }
        public Nullable<decimal> kol515 { get; set; }
        public Nullable<decimal> kolt15k { get; set; }
        public string ct1 { get; set; }
        public string ct2 { get; set; }
        public string ct3 { get; set; }
        public string ct4 { get; set; }
        public string ct5 { get; set; }
    }
}
