//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiKOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KOL()
        {
            this.Anhduocdangs = new HashSet<Anhduocdang>();
            this.BaiVietKOLs = new HashSet<BaiVietKOL>();
            this.fls = new HashSet<fl>();
            this.hopdongs = new HashSet<hopdong>();
            this.linhvucKOLs = new HashSet<linhvucKOL>();
            this.ThoiGianBieuKOLs = new HashSet<ThoiGianBieuKOL>();
            this.ToCaos = new HashSet<ToCao>();
        }
    
        public string id { get; set; }
        public string nickname { get; set; }
        public string ten { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string diachi { get; set; }
        public string sdt { get; set; }
        public Nullable<int> kolcore { get; set; }
        public string linktiktok { get; set; }
        public string malv { get; set; }
        public string gmail { get; set; }
        public string gioithieu { get; set; }
        public string pass { get; set; }
        public string avatar { get; set; }
        public Nullable<int> fltiktok { get; set; }
        public Nullable<int> trangthai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anhduocdang> Anhduocdangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiVietKOL> BaiVietKOLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fl> fls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hopdong> hopdongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<linhvucKOL> linhvucKOLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThoiGianBieuKOL> ThoiGianBieuKOLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToCao> ToCaos { get; set; }
    }
}
