//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiKOL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KOLDbContext : DbContext
    {
        public KOLDbContext()
            : base("name=KOLDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<Anhduocdang> Anhduocdangs { get; set; }
        public virtual DbSet<baiviet> baiviets { get; set; }
        public virtual DbSet<BaiVietKOL> BaiVietKOLs { get; set; }
        public virtual DbSet<BinhLuanBVKOL> BinhLuanBVKOLs { get; set; }
        public virtual DbSet<cautruc> cautrucs { get; set; }
        public virtual DbSet<fl> fls { get; set; }
        public virtual DbSet<hopdong> hopdongs { get; set; }
        public virtual DbSet<khach> khaches { get; set; }
        public virtual DbSet<KOL> KOLs { get; set; }
        public virtual DbSet<linhvuc> linhvucs { get; set; }
        public virtual DbSet<linhvucKhach> linhvucKhaches { get; set; }
        public virtual DbSet<linhvucKOL> linhvucKOLs { get; set; }
        public virtual DbSet<LuotThichBVKOL> LuotThichBVKOLs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<taikhoan> taikhoans { get; set; }
        public virtual DbSet<ThoiGianBieuKOL> ThoiGianBieuKOLs { get; set; }
        public virtual DbSet<ToCao> ToCaos { get; set; }
    }
}
