//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiKOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class linhvucKOL
    {
        public string IdKOL { get; set; }
        public string malv { get; set; }
        public Nullable<int> fl { get; set; }
    
        public virtual KOL KOL { get; set; }
        public virtual linhvuc linhvuc { get; set; }
    }
}
