//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiKOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThoiGianBieuKOL
    {
        public string IdKOL { get; set; }
        public Nullable<System.DateTime> thoigian { get; set; }
        public string hopdong { get; set; }
        public int tutang { get; set; }
    
        public virtual hopdong hopdong1 { get; set; }
        public virtual KOL KOL { get; set; }
    }
}
