//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiKOL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToCao
    {
        public int matocao { get; set; }
        public string Idtocao { get; set; }
        public string idbitocao { get; set; }
        public Nullable<System.DateTime> thoigian { get; set; }
        public string Lido { get; set; }
        public Nullable<int> Trangthai { get; set; }
    
        public virtual KOL KOL { get; set; }
    }
}
